export enum Region {
  Ohio = 'us-east-2',
  NorthVirginia = 'us-east-1',
  NorthCalifornia = 'us-west-1',
  Oregon = 'us-west-2',
  HongKong = 'ap-east-1',
  Mumbai = 'ap-south-1',
  OsakaLocal = 'ap-northeast-3',
  Seoul = 'ap-northeast-2',
  Singapore = 'ap-southeast-1',
  Sydney = 'ap-southeast-2',
  Tokyo = 'ap-northeast-1',
  CanadaCentral = 'ca-central-1',
  Frankfurt = 'eu-central-1',
  Ireland = 'eu-west-1',
  London = 'eu-west-2',
  Paris = 'eu-west-3',
  Stockholm = 'eu-north-1',
  Bahrain = 'me-south-1',
  SãoPaulo = 'sa-east-1'
}