language: node_js

branches:
  only:
    - master

before_script:
  - npm run setup
  - npm run build

script:
  - npm run test

after_success:
  - npm run typedoc
  - codecov
  - npm pack

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: 'aws-lambda-framework-*.tgz'
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    skip_cleanup: true
    email: 'Hjartvar@protonmail.com'
    api_key: $NPM_TOKEN
    on:
      tags: true
